using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IdleGame
{
    public enum UnitType
    {
        Cokka,

    }
    public enum BonusType
    {
        AllDamage,
        AllDamageGear,
        HeroDamage,
        MonsterGold,
        BerserkerRageDuration,
        BerserkerRageCooldown,
        GoldFromChests,
        AllGold,
        ChestChance,
        ChestGold,
        CriticalChance,
        ChanceFor10xGold,
        PlayerDamage,
        PlayerDamageDPS,
        CriticalDamage,
        WarCryCooldown,
        HandOfMidasCooldown,
        ShadowCloneDuration,
        ShadowCloneCooldown,
        CriticalStrikeDuration,
        HandOfMidasDuration,
        UpgradeCost,
        CriticalStrikeCooldown,
        HeavenlyStrikeCooldown,
        BonusRelic,
        WarCryDuration
    }

    public enum GearID
    {
        Gear1,
        Gear2,
        Gear3,
        Gear4,
        Gear5,
        Gear6,
        Gear7,
        Gear8,
        Gear9,
        Gear10,
        Gear11,
        Gear12,
        Gear13,
        Gear14,
        Gear15,
        Gear16,
        Gear17,
        Gear18,
        Gear19,
        Gear20,
        Gear21,
        Gear22,
        Gear23,
        Gear24,
        Gear25,
        Gear26,
        Gear27,
        Gear28,
        Gear29,
        Gear30,
        Gear31,
        Gear32,
        Gear33,
        Gear34,
        Gear35,
        Gear36,
        Gear37,
        Gear38,
        Gear39,
        Gear40,
        Gear41,
        Gear42,
        Gear43,
        Gear44,
        Gear45,
        Gear46,
        Gear47,
        Gear48,
        Gear49,
        Gear50,
        Gear51,
        Gear52,
        Gear53,
        Gear54,
        Gear55,
        Gear56,
        Gear57,
        Gear58,
        Gear59,
        Gear60,
        Gear61,
        Gear62,
        Gear63,
        Gear64,
        Gear65,
        Gear66,
        Gear67,
        Gear68,
        Gear69,
        Gear70
    }
}
